---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-gosec
spec:
  params:
    - name: repo_url
    - name: revision
    - name: target_branch
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: gosec
      taskRef:
        name: gosec
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
